services:
  - type: web
    name: trimmer-yt
    env: node
    plan: free
    buildCommand: |
      npm install --prefix server
      npm install --prefix client
      npm --prefix client run build
    startCommand: npm --prefix server start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: "production"
      - key: PORT
        value: "10000"
      - key: YTDL_NO_UPDATE
        value: "1"
